
# This is a basic workflow to help you get started with Actions

name: Readme Update

# Controls when the workflow will run
on:
# 1시간에 한번씩 아래 스크립트를 실행한다.
  schedule:
    - cron: "0 0 * * *" 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Update README
        run: npm start
      - name: Commit README
        run: |
          git config --local user.email "jinjs6@gmail.com"
          git config --local user.name "core"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m 'Update README with latest blog posts'
            git push
          else
            echo "NO changes to commit"
          fi
        env:
          JS_PERSONAL_TOKEN: ${{ secrets.JS_PERSONAL_TOKEN }}